// Auto-generated metadata for steamapi-xpaw client library
// Source: https://steamapi.xpaw.me/

export const METHOD_VERSIONS = {
  "IDOTA2Match_570/GetTournamentPlayerStats": 2,
  "IDOTA2Operations_570/GetBannedWordList": 2,
  "IEconItems_730/GetSchema": 2,
  "IEconItems_730/GetSchemaURL": 2,
  "ISteamApps/GetPartnerAppListForWebAPIKey": 2,
  "ISteamApps/SetAppBuildLive": 2,
  "ISteamLeaderboards/FindOrCreateLeaderboard": 2,
  "ISteamLeaderboards/GetLeaderboardsForGame": 2,
  "ISteamMicroTxn/FinalizeTxn": 2,
  "ISteamMicroTxn/GetReport": 5,
  "ISteamMicroTxn/GetUserAgreementInfo": 2,
  "ISteamMicroTxn/GetUserInfo": 2,
  "ISteamMicroTxn/InitTxn": 3,
  "ISteamMicroTxn/QueryTxn": 3,
  "ISteamMicroTxn/RefundTxn": 2,
  "ISteamMicroTxnSandbox/FinalizeTxn": 2,
  "ISteamMicroTxnSandbox/GetReport": 5,
  "ISteamMicroTxnSandbox/GetUserAgreementInfo": 2,
  "ISteamMicroTxnSandbox/GetUserInfo": 2,
  "ISteamMicroTxnSandbox/InitTxn": 3,
  "ISteamMicroTxnSandbox/QueryTxn": 3,
  "ISteamMicroTxnSandbox/RefundTxn": 2,
  "ISteamNews/GetNewsForApp": 2,
  "ISteamNews/GetNewsForAppAuthed": 2,
  "ISteamUser/CheckAppOwnership": 4,
  "ISteamUser/GetPlayerSummaries": 2,
  "ISteamUser/GetPublisherAppOwnership": 5,
  "ISteamUser/GrantPackage": 3,
  "ISteamUserStats/GetGlobalAchievementPercentagesForApp": 2,
  "ISteamUserStats/GetSchemaForGame": 2,
  "ISteamUserStats/GetUserStatsForGame": 2,
  "ITFItems_440/GetGoldenWrenches": 2
};

export const PUBLISHER_ONLY = new Set([
  "IBroadcastService/PostGameDataFrame",
  "IChatRoomService/AppAddUsersToGroup",
  "IChatRoomService/AppPostSystemMessageToGroup",
  "IChatRoomService/AppRemoveUsersFromGroup",
  "IChatRoomService/CreateAppChatRoomGroup",
  "IChatRoomService/SetAppChatRoomConfig",
  "ICheatReportingService/EndSecureMultiplayerSession",
  "ICheatReportingService/GetCheatingReports",
  "ICheatReportingService/RemovePlayerGameBan",
  "ICheatReportingService/ReportPlayerCheating",
  "ICheatReportingService/RequestPlayerGameBan",
  "ICheatReportingService/RequestVacStatusForUser",
  "ICheatReportingService/StartSecureMultiplayerSession",
  "IContentFilteringService/FilterStrings",
  "IEconMarketService/CancelAppListingsForUser",
  "IEconMarketService/GetAssetID",
  "IEconMarketService/GetMarketEligibility",
  "IEconMarketService/GetPopular",
  "IEconMarketService/LearnItem",
  "IEconService/FlushAssetAppearanceCache",
  "IEconService/FlushContextCache",
  "IEconService/FlushInventoryCache",
  "IGameInventory/GetHistoryCommandDetails",
  "IGameInventory/GetUserHistory",
  "IGameInventory/HistoryExecuteCommands",
  "IGameInventory/SupportGetAssetHistory",
  "IGameNotificationsService/CreateSession",
  "IGameNotificationsService/DeleteSession",
  "IGameNotificationsService/DeleteSessionBatch",
  "IGameNotificationsService/EnumerateSessionsForApp",
  "IGameNotificationsService/GetSessionDetailsForApp",
  "IGameNotificationsService/RequestNotifications",
  "IGameNotificationsService/UpdateSession",
  "IGameServersService/SetBanStatus",
  "IInventoryService/AddItem",
  "IInventoryService/AddPromoItem",
  "IInventoryService/Consolidate",
  "IInventoryService/ConsolidateAll",
  "IInventoryService/ExchangeItem",
  "IInventoryService/GetAddItemHistory",
  "IInventoryService/GetInventory",
  "IInventoryService/GetItemDefs",
  "IInventoryService/GetQuantity",
  "IInventoryService/ModifyItems",
  "ILobbyMatchmakingService/CreateLobby",
  "ILobbyMatchmakingService/GetLobbyData",
  "ILobbyMatchmakingService/RemoveUserFromLobby",
  "IOnlinePlayService/GetCoPlayStatus",
  "IProductInfoService/SetRichPresenceLocalization",
  "IPublishedFileModerationService/GetAllApprovalRequests",
  "IPublishedFileModerationService/ProcessApprovalRequest",
  "IPublishedFileService/Delete",
  "IPublishedFileService/RefreshVotingQueue",
  "IPublishedFileService/SetDeveloperMetadata",
  "IPublishedFileService/UpdateAppUGCBan",
  "IPublishedFileService/UpdateBanStatus",
  "IPublishedFileService/UpdateIncompatibleStatus",
  "IPublishedFileService/UpdateKeyValueTags",
  "IPublishedFileService/UpdateTags",
  "IPublishedFileService/Vote",
  "IQuestService/PublisherAddCommunityItemsToPlayer",
  "ISteamApps/GetAppBetas",
  "ISteamApps/GetAppBuilds",
  "ISteamApps/GetAppDepotVersions",
  "ISteamApps/GetCheatingReports",
  "ISteamApps/GetPartnerAppListForWebAPIKey",
  "ISteamApps/GetPlayersBanned",
  "ISteamApps/GetServerList",
  "ISteamApps/SetAppBuildLive",
  "ISteamApps/UpdateAppBranchDescription",
  "ISteamCommunity/ReportAbuse",
  "ISteamEconomy/CanTrade",
  "ISteamEconomy/FinalizeAssetTransaction",
  "ISteamEconomy/GetMarketPrices",
  "ISteamEconomy/StartAssetTransaction",
  "ISteamEconomy/StartTrade",
  "ISteamGameServerStats/GetGameServerPlayerStatsForGame",
  "ISteamLeaderboards/DeleteLeaderboard",
  "ISteamLeaderboards/DeleteLeaderboardScore",
  "ISteamLeaderboards/FindOrCreateLeaderboard",
  "ISteamLeaderboards/GetLeaderboardEntries",
  "ISteamLeaderboards/GetLeaderboardsForGame",
  "ISteamLeaderboards/ModifyLeaderboardScoreMulti",
  "ISteamLeaderboards/ResetLeaderboard",
  "ISteamLeaderboards/SetLeaderboardScore",
  "ISteamMicroTxn/AdjustAgreement",
  "ISteamMicroTxn/CancelAgreement",
  "ISteamMicroTxn/FinalizeTxn",
  "ISteamMicroTxn/GetReport",
  "ISteamMicroTxn/GetUserAgreementInfo",
  "ISteamMicroTxn/GetUserInfo",
  "ISteamMicroTxn/InitTxn",
  "ISteamMicroTxn/ProcessAgreement",
  "ISteamMicroTxn/QueryTxn",
  "ISteamMicroTxn/RefundTxn",
  "ISteamMicroTxnSandbox/AdjustAgreement",
  "ISteamMicroTxnSandbox/CancelAgreement",
  "ISteamMicroTxnSandbox/FinalizeTxn",
  "ISteamMicroTxnSandbox/GetReport",
  "ISteamMicroTxnSandbox/GetUserAgreementInfo",
  "ISteamMicroTxnSandbox/GetUserInfo",
  "ISteamMicroTxnSandbox/InitTxn",
  "ISteamMicroTxnSandbox/ProcessAgreement",
  "ISteamMicroTxnSandbox/QueryTxn",
  "ISteamMicroTxnSandbox/RefundTxn",
  "ISteamNews/GetNewsForAppAuthed",
  "ISteamPublishedItemSearch/RankedByPublicationOrder",
  "ISteamPublishedItemSearch/RankedByTrend",
  "ISteamPublishedItemSearch/RankedByVote",
  "ISteamPublishedItemSearch/ResultSetSummary",
  "ISteamPublishedItemVoting/ItemVoteSummary",
  "ISteamPublishedItemVoting/UserVoteSummary",
  "ISteamRemoteStorage/EnumerateUserSubscribedFiles",
  "ISteamRemoteStorage/SetUGCUsedByGC",
  "ISteamRemoteStorage/SubscribePublishedFile",
  "ISteamRemoteStorage/UnsubscribePublishedFile",
  "ISteamSpecialSurvey/CheckUserStatus",
  "ISteamSpecialSurvey/SetUserFinished",
  "ISteamUser/CheckAppOwnership",
  "ISteamUser/GetAppPriceInfo",
  "ISteamUser/GetPublisherAppOwnership",
  "ISteamUser/GetPublisherAppOwnershipChanges",
  "ISteamUser/GrantPackage",
  "ISteamUser/RevokePackage",
  "ISteamUserStats/SetUserStatsForGame",
  "ISteamWorkshop/AssociateWorkshopItems",
  "ISteamWorkshop/GetContributors",
  "ITestExternalPrivilegeService/CallPublisherKey",
  "ITestExternalPrivilegeService/CallPublisherKeyOwnsApp",
  "IVACManagementService/GameModuleLoadReport",
  "IWorkshopService/AddSpecialPayment",
  "IWorkshopService/GetFinalizedContributors",
  "IWorkshopService/GetItemDailyRevenue",
  "IWorkshopService/PopulateItemDescriptions",
  "IWorkshopService/SetItemPaymentRules"
]);
